### ISSUE TITLE
A way to create cifar_train.npz

### ISSUE THREAD

**Issue by KevinWang676** [forever208/DDPM-IP#11]
Hi, I wrote [cifar10_npz.py](https://colab.research.google.com/drive/1-F_AvjrGnu8LfuwgI-itc7L_jvv_fjV9?usp=sharing) in order to create the npz file of cifar10 dateset. The code is basically the same as your [celeba64_npz.py](https://github.com/forever208/DDPM-IP/blob/DDPM-IP/datasets/celeba64_npz.py) and I just modified the names in the code and set the image size to 32×32. I wonder if this method can lead to the correct npz file of cifar10 dateset since I'm not sure if the structure of the two datasets (cifar10 and celeba) is the same. Thanks again!

Here is the [link](https://colab.research.google.com/drive/1-F_AvjrGnu8LfuwgI-itc7L_jvv_fjV9?usp=sharing) to the code.

**Comment by KevinWang676** [comment]
Also, I wonder what the number of training steps is. I've trained the model for over 100k steps, and it's still running. Thanks!

![image](https://github.com/forever208/DDPM-IP/assets/126712357/7da60c41-21d6-443f-896d-8cd91516242e)

**Comment by forever208** [comment]
> Hi, I wrote [cifar10_npz.py](https://colab.research.google.com/drive/1-F_AvjrGnu8LfuwgI-itc7L_jvv_fjV9?usp=sharing) in order to create the npz file of cifar10 dateset. The code is basically the same as your [celeba64_npz.py](https://github.com/forever208/DDPM-IP/blob/DDPM-IP/datasets/celeba64_npz.py) and I just modified the names in the code and set the image size to 32×32. I wonder if this method can lead to the correct npz file of cifar10 dateset since I'm not sure if the structure of the two datasets (cifar10 and celeba) is the same. Thanks again!
> 
> Here is the [link](https://colab.research.google.com/drive/1-F_AvjrGnu8LfuwgI-itc7L_jvv_fjV9?usp=sharing) to the code.

Your code looks correct and the cifar npz file should work for the FID computation.
I will add the npz-transformation code to the repo later.

**Comment by forever208** [comment]
> Also, I wonder what the number of training steps is. I've trained the model for over 100k steps, and it's still running. Thanks!
> 
> ![image](https://user-images.githubusercontent.com/126712357/240089576-7da60c41-21d6-443f-896d-8cd91516242e.png)

I trained cifar-10 for 500k steps with batch_size=128, DDPM-IP converges around 460k, DDPM converges around 500k

**Comment by KevinWang676** [comment]
Got it, thank you!

**Comment by KevinWang676** [comment]
> I trained cifar-10 for 500k steps with batch_size=128, DDPM-IP converges around 460k, DDPM converges around 500k

Hi, I wonder if you mean `total_batch_size=128` by saying `batch_size=128`. Thank you!

**Comment by forever208** [comment]
total batch size = 128
