### ISSUE TITLE
Line 868: noise = th.randn_like(x_start) remains unchanged

### ISSUE THREAD

**Issue by KevinWang676** [forever208/DDPM-IP#12]
Hi, I found that in line [204](https://github.com/forever208/DDPM-IP/blob/d99d89857e2866271e130be788256256ade83482/guided_diffusion/gaussian_diffusion.py#L204) and [868](https://github.com/forever208/DDPM-IP/blob/d99d89857e2866271e130be788256256ade83482/guided_diffusion/gaussian_diffusion.py#L868) of [guided_diffusion/gaussian_diffusion.py](https://github.com/forever208/DDPM-IP/blob/DDPM-IP/guided_diffusion/gaussian_diffusion.py), the code `noise = th.randn_like(x_start)` remains unchanged. Shouldn't we have `new_noise = noise + gamma * th.randn_like(noise)` in line 868 as well? Or it doesn't matter. Thanks!

**Comment by KevinWang676** [comment]
In line 204, I think it's okay to remain unchanged, but in line 868 I'm not sure if it's necessary to update the code (add new_noise).

**Comment by KevinWang676** [comment]
Also, I wonder if ImageNet 32x32 dataset for training is the one I highlighted in the picture below. Thank you!

![image](https://github.com/forever208/DDPM-IP/assets/126712357/b39e0c40-03c5-409c-ab89-e8e11bb9a1ae)

**Comment by forever208** [comment]
> Hi, I found that in line [204](https://github.com/forever208/DDPM-IP/blob/d99d89857e2866271e130be788256256ade83482/guided_diffusion/gaussian_diffusion.py#L204) and [868](https://github.com/forever208/DDPM-IP/blob/d99d89857e2866271e130be788256256ade83482/guided_diffusion/gaussian_diffusion.py#L868) of [guided_diffusion/gaussian_diffusion.py](https://github.com/forever208/DDPM-IP/blob/DDPM-IP/guided_diffusion/gaussian_diffusion.py), the code `noise = th.randn_like(x_start)` remains unchanged. Shouldn't we have `new_noise = noise + gamma * th.randn_like(noise)` in line 868 as well? Or it doesn't matter. Thanks!

The only change our method makes and should only make is inside the `training_losses` function since our method is a training regularization

**Comment by forever208** [comment]
> Also, I wonder if ImageNet 32x32 dataset for training is the one I highlighted in the picture below. Thank you!
> 
> ![image](https://user-images.githubusercontent.com/126712357/240482382-b39e0c40-03c5-409c-ab89-e8e11bb9a1ae.png)

@KevinWang676 Correct

**Comment by KevinWang676** [comment]
Thanks for your reply!
