### ISSUE TITLE
train_data_batch in imagenet32 is not npz file

### ISSUE THREAD

**Issue by KevinWang676** [forever208/DDPM-IP#13]
Hi, the 10 train_data_batch in Imagenet32_train.zip downloaded online is not npz file, so the code ([line 2](https://github.com/forever208/DDPM-IP/blob/d99d89857e2866271e130be788256256ade83482/datasets/imagenet32_npz.py#L11)) in [datasets/imagenet32_npz.py](https://github.com/forever208/DDPM-IP/blob/d99d89857e2866271e130be788256256ade83482/datasets/imagenet32_npz.py) doesn't work. I tried to modify the code to make it work. Here are two modifications I make: `filename = './ImageNet32/train_data_batch_' + str(i)` and `raw_data = np.load(filename, allow_pickle=True)`. Please doulbe check my code. Thanks!

![image](https://github.com/forever208/DDPM-IP/assets/126712357/91b2ad90-e85c-4c74-9a4b-35fa672901f8)

**Comment by KevinWang676** [comment]
I figured it out. I need to download the npz version of Imagenet32. Thanks.

**Comment by forever208** [comment]
@KevinWang676 training ImageNet32 takes me a month using 4V100 GPUs. It is suggested to first train on other datasets

**Comment by KevinWang676** [comment]
I see, thank you! I'm now working on training the model of cifar10 using your code.

**Comment by KevinWang676** [comment]
By the way, I wonder if multi-node training will lead to a different model from single node multi GPU training. I'm now on 4V100 GPUs and a single node.

**Comment by forever208** [comment]
> By the way, I wonder if multi-node training will lead to a different model from single node multi GPU training. I'm now on 4V100 GPUs and a single node.

no difference
