### ISSUE TITLE
A discrepancy between the table in the paper and the figure in the repo

### ISSUE THREAD

**Issue by KevinWang676** [forever208/DDPM-IP#16]
Hi, I found that in your paper (Table 3) the FID scores of CIFAR10 32×32 are all above 3, but in your repo the FID score is less than 2.5. So I wonder what the FID score of CIFAR10 32×32 is exactly.

![image](https://github.com/forever208/DDPM-IP/assets/126712357/1c5d1e6c-f2f5-4ee5-868a-cd6a73ace6ee)
![image](https://github.com/forever208/DDPM-IP/assets/126712357/700cfcd3-e4f5-403f-bddb-241e5e4560eb)

**Comment by forever208** [comment]
@KevinWang676 the repo figures are correct, the paper will be updated soon
