### ISSUE TITLE
Something Wrong in imagenet32_npz.py

### ISSUE THREAD

**Issue by RachelTeamo** [forever208/DDPM-IP#23]
I'm sorry to bother you again, but I'm getting an error when making an npz file of Imagenet32 data!
https://github.com/forever208/DDPM-IP/blob/DDPM-IP/datasets/imagenet32_npz.py#L19
```
ValueError: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 1, the array at index 0 has size 1024 and the array at index 2 has size 10240
```
I found the dimension of x[:, 2 * 1024:] to be (128116, 10240), which doesn't seem to match the previous one.

**Comment by forever208** [comment]
@RachelTeamo hi, the three components inside `x = np.dstack((x[:, :1024], x[:, 1024:2 * 1024], x[:, 2 * 1024:]))` should have the same shape (128116, 1024).
Namely, `x[:, :1024]`, `x[:, 1024:2 * 1024]`  and `x[:, 2 * 1024:]` are with the same shape.
We do not have to use `x[:, 2 * 1024:]` here.

**Comment by RachelTeamo** [comment]
I know the problem because I downloaded the 64-resolution dataset.  Thanks again~
