### ISSUE TITLE
Noisy Images when training on custom dataset

### ISSUE THREAD

**Issue by lsch0lz** [forever208/DDPM-IP#24]
When I try to train a model on my own dataset, with the command for the FFHQ 128x128 dataset I get really noisy images, even after 90000 steps:
<img width="458" alt="Bildschirmfoto 2024-01-02 um 09 26 28" src="https://github.com/forever208/DDPM-IP/assets/40420097/f5743e7b-c25d-4a61-b38e-245055be1224">

The custom dataset I want to train on is the [NCT-CRC-HE-100K](https://paperswithcode.com/dataset/nct-crc-he-100k) dataset. The images in the dataset are 224x224, but for me 128x128 would be enough. 

Do you have any ideas why I get those noisy images, instead of better quality?

Here is the command that i use for training:
```
mpirun -n 3 python scripts/image_train.py --input_pertub 0.1 --data_dir /home/tmp/scholuka/NCT_PNG/ADI/ --image_size 128 --use_fp16 True --num_channels 256 --num_head_channels 64 --num_res_blocks 3 --attention_resolutions 32,16,8 --resblock_updown True --use_new_attention_order True --learn_sigma True --dropout 0.1 --diffusion_steps 1000 --noise_schedule cosine --use_scale_shift_norm True --rescale_learned_sigmas True --schedule_sampler loss-second-moment --lr 1e-4 --batch_size 8 --save_interval 1000
```
Here is the command that i use for generation:
```
mpirun -n 3 python scripts/image_sample.py --image_size 128 --timestep_respacing 100 --model_path /vol/tmp/scholuka/diffusion/DDPM-IP/openai-2024-01-01-19-40-18-680385/model099000.pt --use_fp16 True --num_channels 256 --num_head_channels 64 --num_res_blocks 3 --attention_resolutions 32,16,8 --resblock_updown True --use_new_attention_order True --learn_sigma True --dropout 0.1 --diffusion_steps 100 --noise_schedule cosine --use_scale_shift_norm True --rescale_learned_sigmas True --batch_size 128 --num_samples 50
```

Edit: The images in question should look like this:
![ADI-RFMDASRN](https://github.com/forever208/DDPM-IP/assets/40420097/2b5bff96-4339-4538-9114-97f57f551adc)

**Comment by forever208** [comment]
@lsch0lz Hi, instead of using `model099000.pt`  can you try the generation with the corresponding ema checkpoint?

**Comment by lsch0lz** [comment]
Unfortunately i get the same noisy images with the ema checkpoints:

```
mpirun -n 3 python scripts/image_sample.py --image_size 128 --timestep_respacing 100 --model_path /vol/tmp/scholuka/diffusion/DDPM-IP/openai-2024-01-03-22-11-20-724716/ema_0.9999_020000.pt --use_fp16 True --num_channels 256 --num_head_channels 64 --num_res_blocks 3 --attention_resolutions 32,16,8 --resblock_updown True --use_new_attention_order True --learn_sigma True --dropout 0.1 --diffusion_steps 100 --noise_schedule cosine --use_scale_shift_norm True --rescale_learned_sigmas True --batch_size 128 --num_samples 50
Logging to /tmp/openai-2024-01-04-10-11-07-936223
creating model and diffusion...
input perturbation is: 0.0
input perturbation is: 0.0
loading checkpoint: /vol/tmp/scholuka/diffusion/DDPM-IP/openai-2024-01-03-22-11-20-724716/ema_0.9999_020000.pt
timesteps: 100
sampling...
^A^Acreated 384 samples
saving to /tmp/openai-2024-01-04-10-11-07-936223/samples_50x128x128x3.npz
sampling complete
```
Ema Image:
<img width="459" alt="ema" src="https://github.com/forever208/DDPM-IP/assets/40420097/be4fbaf4-7075-4e3b-bffb-59e578b0c740">

Model Image:
<img width="460" alt="model" src="https://github.com/forever208/DDPM-IP/assets/40420097/7a100aa7-c91b-4fe1-9da6-cb2a62f31e92">

**Comment by forever208** [comment]
@lsch0lz during the training, can you try with a larger batch size? e.g. 64
then do the training about 10k steps, and see what the generated images look like
