### ISSUE TITLE
ModuleNotFoundError: No module named 'guided_diffusion'

### ISSUE THREAD

**Issue by EudicL** [forever208/DDPM-IP#29]
mpirun python3  scripts/image_sample.py \
--image_size 32 --timestep_respacing 100 \
--model_path PATH_TO_CHECKPOINT \
--num_channels 128 --num_head_channels 32 --num_res_blocks 3 --attention_resolutions 16,8 \
--resblock_updown True --use_new_attention_order True --learn_sigma True --dropout 0.3 \
--diffusion_steps 1000 --noise_schedule cosine --use_scale_shift_norm True --batch_size 256 --num_samples 50000

**Comment by forever208** [comment]
`pip install -e .` should fix this installation issue
