### ISSUE TITLE
Do the trick related to noise offset

### ISSUE THREAD

**Issue by xiaohu2015** [forever208/DDPM-IP#7]
https://www.crosslabs.org//blog/diffusion-with-offset-noise
@forever208

**Comment by forever208** [comment]
@xiaohu2015  Thanks for your mentioned interesting blog. DDPM-IP has nothing to do with offset noise.
If you look at their offset noise `noise = torch.randn_like(latents) + 0.1 * torch.randn(latents.shape[0], latents.shape[1], 1, 1)`, they add the same value for each pixel for a channel to implement the drift. Whereas, our is `new_noise = noise + 0.1 * th.randn_like(noise)`.

More importantly, I think their input signal and target signal are both `noise = torch.randn_like(latents) + 0.1 * torch.randn(latents.shape[0], latents.shape[1], 1, 1)` during training. This is not the case for DDPM-IP
