### ISSUE TITLE
A Error “mpirun: command not found”

### ISSUE THREAD

**Issue by KevinWang676** [forever208/DDPM-IP#8]
I got an error named “mpirun: command not found” when I ran the code below:

![image](https://github.com/forever208/DDPM-IP/assets/126712357/a39bc29f-a449-48cd-9ccd-e6b73cb94b91)
 
And here is my attempt to sample from the pre-trained ADM-IP model (I put DDPM_IP_cifar10.pt under the “model” folder):

![be4bb32826efcbbdd614b4d1e4006ee](https://github.com/forever208/DDPM-IP/assets/126712357/88abc00e-ff82-4aa8-a70d-37bf2d0bd04d)

Could you tell me which step I did wrong? Thanks for your time!

**Comment by forever208** [comment]
@KevinWang676 you need to install mpi, try `pip install mpi4py`

**Comment by KevinWang676** [comment]
Hi, I tried "pip install mpi4py", but it failed. I also installed PEP517, but there was still the same error as shown below.

![image](https://github.com/forever208/DDPM-IP/assets/126712357/66316f28-91ab-41cb-ab28-8456aeec2654)

Could you help me resolve it? Thanks!

**Comment by forever208** [comment]
@KevinWang676 I don't remember the exact way of solving this issue when I had it.
I can provide you some resources I used for tackling this problem:
https://stackoverflow.com/questions/28440834/error-when-installing-mpi4py
https://mpi4py.readthedocs.io/en/stable/tutorial.html#running-python-scripts-with-mpi
http://linuxdesktops.soton.ac.uk/openmpi.html

**Comment by KevinWang676** [comment]
Thanks, I'll check this out. Also, could you provide the code of calculating FID of the generated images? This will help the future improvements. Thanks!

**Comment by forever208** [comment]
@KevinWang676 please go the folder `evaluation` for the code and instructions.
We use the FID-computing code from ADM without any change

**Comment by KevinWang676** [comment]
I found it, thank you! By the way, I think your email address in this paper is not valid. Will you update your email address here? Because I may have some further questions about your paper.

**Comment by KevinWang676** [comment]
Hi, I found the solution to the problem. Just simply run the code below:

![image](https://github.com/forever208/DDPM-IP/assets/126712357/dbc1f1ea-3a7c-4e8d-af49-3fa136b4c5b5)

Thanks for your help!

**Comment by forever208** [comment]
@KevinWang676 you can contact me by `m.ning@uu.nl`
