### ISSUE TITLE
Cannot find the output of sampling

### ISSUE THREAD

**Issue by KevinWang676** [forever208/DDPM-IP#9]
Hi, I've finished sampling from the pretrained model, but I don't see the output npz file. There is no folder called "/tmp/openai..." in my interface. I wonder how I can find the npz file. Thanks!

This is what I got:
![image](https://github.com/forever208/DDPM-IP/assets/126712357/962f27b5-9d77-4c2f-ba4f-20e639dd25e7)

**Comment by forever208** [comment]
@KevinWang676 the `tmp` folder is parallel with your `home` folder in linux.

you can set the sampling folder by setting the env variable: `export OPENAI_LOGDIR=YOUR_PATH`

**Comment by KevinWang676** [comment]
Thank you! I exported the files successfully. I moved on to the evaluation part and I wonder where I can find the corresponding npz files of the datasets like CIFAR10 and CelebA. I downloaded cifar-10.npz from this [link](https://www.kaggle.com/datasets/guesejustin/cifar10-keras-files-cifar10load-data), but there was no "arr_0" in this npz file as shown below.
![image](https://github.com/forever208/DDPM-IP/assets/126712357/03f9fa9f-f39d-4e74-951c-a4336ab36a1c)

Could you tell me where to download the correct npz files? Thanks!

**Comment by KevinWang676** [comment]
By the way, the four items in my cifar-10.npz are x_train, y_train, x_test, y_test and there is no arr_0. Thanks.
![image](https://github.com/forever208/DDPM-IP/assets/126712357/6da5919f-90d2-4d32-8bca-27973c7560c6)

**Comment by forever208** [comment]
@KevinWang676 You can directly download the cifar10 dataset from this script [cifar10.py](https://github.com/forever208/DDPM-IP/blob/DDPM-IP/datasets/cifar10.py)

Refer to the [readme ](https://github.com/forever208/DDPM-IP/tree/DDPM-IP/datasets) for more dataset downloading

When computing FID, transform the training dataset into a numpy `.npz` file

**Comment by KevinWang676** [comment]
Thanks! I've created cifar_train.npz successfully. I wonder if I need to combine cifar_train.npz and cifar_test.npz when computing FID. Because the reference batch may need to contain both of them. Am I right? Thank you.

**Comment by forever208** [comment]
@KevinWang676 in most generative papers, people only use the training set for training and FID-computing
